### ISSUE TITLE
Only working in Chrome

### ISSUE THREAD

**Issue by faburem** [aruntk/kickstart-meteor-polymer#1]
While everything is working fine in Chrome, I wasn't able to get this to work in Firefox or Safari. There seems to be a load order / import problem. Any thoughts on this?
<img width="959" alt="screen shot 2016-04-15 at 12 29 40" src="https://cloud.githubusercontent.com/assets/11456790/14558993/32785eec-0306-11e6-80ae-a8c8e30646f2.png">

**Comment by aruntk** [comment]
@faburem Now works in firefox latest version.

**Comment by faburem** [comment]
confirmed, it is working now. Thanks for the quick fix!

**Comment by aruntk** [comment]
@faburem you're welcome. :)
