### ISSUE TITLE
How to use Jade?

### ISSUE THREAD

**Issue by comerc** [aruntk/kickstart-meteor-polymer#3]
Please help me! :)

**Comment by aruntk** [comment]
I've added a beta package https://github.com/meteorwebcomponents/synthesis/tree/master/packages/synthesis-jade. Its not in atmosphere. So you should clone from git. It converts jade to html and calls synthesis compiler to process the html. But I'm not sure how to add features like extends and include. I'm not very familiar with jade. So If you could help that would be great. The following package can be used as a reference. https://github.com/mquandalle/meteor-jade

**Comment by aruntk** [comment]
basic demo https://github.com/meteorwebcomponents/synthesis-demo/tree/jade

Here is the test file https://github.com/meteorwebcomponents/synthesis-demo/blob/jade/imports/ui/components/test-element.jade

**Comment by comerc** [comment]
https://github.com/pbastowski/meteor-jade-templates/issues/1
https://github.com/civilframe/meteor-angular-jade/issues/14
