### ISSUE TITLE
Polymer 2.0 Unable to resolve vertx

### ISSUE THREAD

**Issue by yorrd** [aruntk/kickstart-meteor-polymer#5]
Hi. I tried to update to 2.0 today (@aruntk mentioned in an earlier issue this should be just fine). So I basically only updated the dependencies to the preview version and started this demo via `meteor run`. Server console:

Unable to resolve some modules:

```
  "vertx" in
/home/yorrd/PhpstormProjects/conboxr/imports/ui/bower_components/webcomponentsjs/webcomponents-lite.js
(web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save vertx
```

Parts of the client console:

```
Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
    at new DomModule (app.js?hash=629d72b…:87)
    at _synthesizer.render (synthesis-client.js:10)
    at meteorInstall.imports.ui.layouts.template.test-layout.js (app.js?hash=629d72b…:10641)
    at fileEvaluate (modules-runtime.js?hash=2b888cb…:207)
    at require (modules-runtime.js?hash=2b888cb…:130)
    at meteorInstall.imports.ui.layouts.test-layout.html (app.js?hash=629d72b…:10622)
    at fileEvaluate (modules-runtime.js?hash=2b888cb…:207)
    at require (modules-runtime.js?hash=2b888cb…:130)
    at meteorInstall.imports.ui.template.index.js (app.js?hash=629d72b…:10753)
    at fileEvaluate (modules-runtime.js?hash=2b888cb…:207)
```

For your convenience, my `bower.json`:
```
{
  "dependencies": {
    "iron-flex-layout": "PolymerElements/iron-flex-layout#2.0-preview",
    "iron-pages": "PolymerElements/iron-pages#2.0-preview",
    "polymer": "Polymer/polymer#^2.0.0-rc.1",
    "app-route": "PolymerElements/app-route#2.0-preview",
    "paper-button": "PolymerElements/paper-button#2.0-preview"
  },
  "name": "synthesis-demo",
  "version": "0.0.1",
  "resolutions": {
    "polymer": "Polymer/polymer#^2.0.0-rc.1",
    "webcomponentsjs": "^v1.0.0-rc.5"
  }
}
```

Can you reproduce this?

Please let me know if I can provide you with any further information :)

EDIT: I'm really confused because I don't see why webcomponentsjs needs vertx anyways, but that's another question entirely. It does at some point call `require("vertx")` but doesn't have any dependency listed in the bower.json

**Comment by aruntk** [comment]
@yorrd This happens when you babel(meteor transpiles es6 to es5) the polymer 2.0 code. Solution is to load es5 adapter script. Example https://github.com/aruntk/kickstart-meteor-polymer-with-app-route/tree/2.0-preview

**Comment by yorrd** [comment]
@aruntk https://www.youtube.com/watch?v=mNU3aIJs88g&feature=youtu.be&t=1m3s
